routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'Controller@index');
Route::get('/privacy', 'Controller@privacy');
Route::get('/termsofuse', 'Controller@terms');
Route::get('/faq', 'Controller@faq');
Route::post('/searchresult', 'Controller@find')->name('searchresult');
Route::get('/loadresult','Controller@ajaxPageLoading')->name('loadresult');
Route::get('/getSeatLayout','Controller@getBusLayout');

Auth::routes();

Route::get('/resetPassword','Auth\ForgotPasswordController@showResetUI')->name('resetPassword');
Route::post('/resetPassword','Auth\ForgotPasswordController@sendResetedPassword');

Route::get('/home', 'HomeController@index')->name('dashboard');
Route::post('/update-profile','HomeController@updateProfile')->name('post_update_profile');
Route::post('/update-password','HomeController@updatePassword')->name('post_update_password');

Route::get('sell-ticket','Controller@sellTicket')->name('sellTicket');
Route::post('sell-ticket','Controller@addTicket')->name('post_sellTicket');
Route::get('/search-city','Controller@searchCity')->name('search-city');
Route::get('/search-city1','Controller@searchCity1')->name('search-city1');
Route::post('/subscribe','Controller@subscribe')->name('subscribe');
Route::post('/feedback','Controller@feedback')->name('feedback');
Route::post('/request-ticket','Controller@requestTicket')->name('request-ticket');

Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('admin/', 'Admin\LoginController@showLogin');
Route::post('admin/login', 'Admin\LoginController@login')->name('admin.login');

Route::middleware(['admin'])->prefix('admin')->name('admin.')->group(function () {
    //User Settings
    Route::get('/home', 'Admin\AdminController@index')->name('home');
    Route::post('/update_name_email','Admin\AdminController@updateUsername_Email')->name('update.name.email');
    Route::post('/update_password','Admin\AdminController@updatePassword')->name('update.password');
    Route::get('/logout', 'Admin\LoginController@logout')->name('logout');

    //Ticket Resource
    Route::resource('ticket','Admin\TicketController');
    Route::post('ticket/update_status','Admin\TicketController@updateStatus')->name('ticket.update_status');

    Route::get('user/','Admin\UserController@index')->name('user.index');
    Route::post('user/update_status','Admin\UserController@updateStatus')->name('user.update_status');

    Route::get('feedback/','Admin\FeedbackController@index')->name('feedback.index');
    Route::get('feedback/{feedback}/show','Admin\FeedbackController@show')->name('feedback.show');
    Route::get('feedback/{feedback}/destroy','Admin\FeedbackController@destroy')->name('feedback.destroy');

    Route::get('faq','Admin\FaqController@index')->name('faq.index');
    Route::get('faq/{faq}/destroy','Admin\FaqController@destroy')->name('faq.destroy');
    Route::get('faq/{faq}/edit','Admin\FaqController@edit')->name('faq.edit');
    Route::post('faq/{faq}/update','Admin\FaqController@update')->name('faq.update');
    Route::post('faq/insert','Admin\FaqController@insert')->name('faq.insert');
    Route::get('faq/add','Admin\FaqController@add')->name('faq.add');

    Route::get('subscribe','Admin\SubscribeController@index')->name('subscribe.index');
    Route::get('subscribe/{subscribe}.destroy','Admin\SubscribeController@destroy')->name('subscribe.destroy');

    Route::get('bustype' , 'Admin\BusTypeController@index')->name('bustype.index');
    Route::post('bustype/add' , 'Admin\BusTypeController@insert')->name('bustype.insert');
    Route::get('bustype/{bustype}/destroy','Admin\BusTypeController@destroy')->name('bustype.destroy');
    Route::get('bustype/{bustype}/edit','Admin\BusTypeController@edit')->name('bustype.edit');
    Route::post('bustype/{bustype}/update','Admin\BusTypeController@update')->name('bustype.update');

    Route::get('busoperator' , 'Admin\BusOperatorController@index')->name('busoperator.index');
    Route::post('busoperator/add' , 'Admin\BusOperatorController@insert')->name('busoperator.insert');
    Route::get('busoperator/{busoperator}/destroy','Admin\BusOperatorController@destroy')->name('busoperator.destroy');
    Route::get('busoperator/{busoperator}/edit','Admin\BusOperatorController@edit')->name('busoperator.edit');
    Route::post('busoperator/{busoperator}/update','Admin\BusOperatorController@update')->name('busoperator.update');
});

resources/views/admin/home.blade.php
@extends('layouts.adminapp')

@section('content')
<div class="app-title">
  <div>
    <h1><i class="fa fa-dashboard"></i> Settings</h1>
    <p>Setting page for admin</p>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="tile user-settings">
      <h4 class="line-head">Update UserName and Email</h4>
      <form action="{{route('admin.update.name.email')}}" method="post">
        {{csrf_field()}}
        <div class="row mb-4">
          <div class="col-md-12">
            <label>User Name</label>
            <input class="form-control" name="username" value="{{session('admin_username')}}" type="text" required>
          </div>
          <div class="col-md-12">
            <label>Email</label>
            <input class="form-control" name="email" value="{{session('admin_email')}}" type="email" required>
          </div>
        </div>
        <div class="row mb-10">
          <div class="col-md-12">
            <button class="btn btn-primary"><i class="fa fa-fw fa-lg fa-check-circle"></i> Save</button>
          </div>
        </div>
      </form>
    </div>
    <div class="tile user-settings">
      <h4 class="line-head">Update Password</h4>
      <form method="post" action="{{route('admin.update.password')}}">
        {{csrf_field()}}
        <div class="row mb-4">
          <div class="col-md-12">
            <label>Current Password</label>
            <input class="form-control" name="current_password" type="password" required>
            @if(Session::has('current_password'))
              <p class="text-danger">{{Session::get('current_password')}}</p>
            @endif
          </div>
          <div class="col-md-12">
            <label>New Password</label>
            <input class="form-control" name="new_password" type="password" required>
          </div>
          <div class="col-md-12">
            <label>Confirm New Password</label>
            <input class="form-control" name="new_password_confirmation" type="password" required>
            @if($errors->has('new_password'))
              <p class="text-danger">{{$errors->first('new_password')}}</p>
            @endif
          </div>
        </div>
        <div class="row mb-10">
          <div class="col-md-12">
            <button class="btn btn-primary"><i class="fa fa-fw fa-lg fa-check-circle"></i> Save</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Main CSS-->
    <link rel="stylesheet" type="text/css" href="{{asset('admin_assets/css/main.css')}}">
    <!-- Font-icon css-->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Login - TicketMeMe Admin</title>
  </head>
  <body>
    <section class="material-half-bg">
      <div class="cover"></div>
    </section>
    <section class="login-content">
      <div class="logo">
        <h1>TicketMeMe</h1>
      </div>
      <div class="login-box">
        <form class="login-form" action="{{route('admin.login')}}" method="post">
          {{csrf_field()}}
          <h3 class="login-head"><i class="fa fa-lg fa-fw fa-user"></i>SIGN IN</h3>
          <div class="form-group">
            <label class="control-label">Email</label>
            <input class="form-control" name="email" type="email" placeholder="Email" autofocus required>
          </div>
          <div class="form-group">
            <label class="control-label">PASSWORD</label>
            <input class="form-control" type="password" name="password" placeholder="Password" required>
          </div>
          <div class="form-group">
            <div class="utility">
              <div class="animated-checkbox">
                <label>
                  <input type="checkbox"><span class="label-text">Stay Signed in</span>
                </label>
              </div>
            </div>
          </div>
          <div class="form-group btn-container">
            <button class="btn btn-primary btn-block"><i class="fa fa-sign-in fa-lg fa-fw"></i>SIGN IN</button>
          </div>
        </form>
      </div>
    </section>
    <!-- Essential javascripts for application to work-->
    <script src="{{asset('admin_assets/js/jquery-3.2.1.min.js')}}"></script>
    <script src="{{asset('admin_assets/js/popper.min.js')}}"></script>
    <script src="{{asset('admin_assets/js/bootstrap.min.js')}}"></script>
    <script src="{{asset('admin_assets/js/main.js')}}"></script>
    <!-- The javascript plugin to display page loading on top-->
    <script src="{{asset('admin_assets/js/plugins/pace.min.js')}}"></script>
    <script type="text/javascript">
      // Login Page Flipbox control
      $('.login-content [data-toggle="flip"]').click(function() {
      	$('.login-box').toggleClass('flipped');
      	return false;
      });
    </script>
  </body>
</html>