routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'Controller@index');
Route::get('/privacy', 'Controller@privacy');
Route::get('/termsofuse', 'Controller@terms');
Route::get('/faq', 'Controller@faq');
Route::post('/searchresult', 'Controller@find')->name('searchresult');
Route::get('/loadresult','Controller@ajaxPageLoading')->name('loadresult');
Route::get('/getSeatLayout','Controller@getBusLayout');

Auth::routes();

Route::get('/resetPassword','Auth\ForgotPasswordController@showResetUI')->name('resetPassword');
Route::post('/resetPassword','Auth\ForgotPasswordController@sendResetedPassword');

Route::get('/home', 'HomeController@index')->name('dashboard');
Route::post('/update-profile','HomeController@updateProfile')->name('post_update_profile');
Route::post('/update-password','HomeController@updatePassword')->name('post_update_password');

Route::get('sell-ticket','Controller@sellTicket')->name('sellTicket');
Route::post('sell-ticket','Controller@addTicket')->name('post_sellTicket');
Route::get('/search-city','Controller@searchCity')->name('search-city');
Route::get('/search-city1','Controller@searchCity1')->name('search-city1');
Route::post('/subscribe','Controller@subscribe')->name('subscribe');
Route::post('/feedback','Controller@feedback')->name('feedback');
Route::post('/request-ticket','Controller@requestTicket')->name('request-ticket');

Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('admin/', 'Admin\LoginController@showLogin');
Route::post('admin/login', 'Admin\LoginController@login')->name('admin.login');

Route::middleware(['admin'])->prefix('admin')->name('admin.')->group(function () {
    //User Settings
    Route::get('/home', 'Admin\AdminController@index')->name('home');
    Route::post('/update_name_email','Admin\AdminController@updateUsername_Email')->name('update.name.email');
    Route::post('/update_password','Admin\AdminController@updatePassword')->name('update.password');
    Route::get('/logout', 'Admin\LoginController@logout')->name('logout');

    //Ticket Resource
    Route::resource('ticket','Admin\TicketController');
    Route::post('ticket/update_status','Admin\TicketController@updateStatus')->name('ticket.update_status');

    Route::get('user/','Admin\UserController@index')->name('user.index');
    Route::post('user/update_status','Admin\UserController@updateStatus')->name('user.update_status');

    Route::get('feedback/','Admin\FeedbackController@index')->name('feedback.index');
    Route::get('feedback/{feedback}/show','Admin\FeedbackController@show')->name('feedback.show');
    Route::get('feedback/{feedback}/destroy','Admin\FeedbackController@destroy')->name('feedback.destroy');

    Route::get('faq','Admin\FaqController@index')->name('faq.index');
    Route::get('faq/{faq}/destroy','Admin\FaqController@destroy')->name('faq.destroy');
    Route::get('faq/{faq}/edit','Admin\FaqController@edit')->name('faq.edit');
    Route::post('faq/{faq}/update','Admin\FaqController@update')->name('faq.update');
    Route::post('faq/insert','Admin\FaqController@insert')->name('faq.insert');
    Route::get('faq/add','Admin\FaqController@add')->name('faq.add');

    Route::get('subscribe','Admin\SubscribeController@index')->name('subscribe.index');
    Route::get('subscribe/{subscribe}.destroy','Admin\SubscribeController@destroy')->name('subscribe.destroy');

    Route::get('bustype' , 'Admin\BusTypeController@index')->name('bustype.index');
    Route::post('bustype/add' , 'Admin\BusTypeController@insert')->name('bustype.insert');
    Route::get('bustype/{bustype}/destroy','Admin\BusTypeController@destroy')->name('bustype.destroy');
    Route::get('bustype/{bustype}/edit','Admin\BusTypeController@edit')->name('bustype.edit');
    Route::post('bustype/{bustype}/update','Admin\BusTypeController@update')->name('bustype.update');

    Route::get('busoperator' , 'Admin\BusOperatorController@index')->name('busoperator.index');
    Route::post('busoperator/add' , 'Admin\BusOperatorController@insert')->name('busoperator.insert');
    Route::get('busoperator/{busoperator}/destroy','Admin\BusOperatorController@destroy')->name('busoperator.destroy');
    Route::get('busoperator/{busoperator}/edit','Admin\BusOperatorController@edit')->name('busoperator.edit');
    Route::post('busoperator/{busoperator}/update','Admin\BusOperatorController@update')->name('busoperator.update');
});

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    //
    protected $guarded = ['id'];
    public function user(){
        return $this->belongsTo('App\User');
    }
    public function destination()
    {
        return $this->belongsTo('App\City','destination_id');
    }
    public function source()
    {
        return $this->belongsTo('App\City','source_id');
    }
    public function bus_operator()
    {
        return $this->belongsTo('App\BusOperator');
    }
    public function bus_type()
    {
        return $this->belongsTo('App\BusType');
    }
}

app/Http/Controllers/Admin/TicketController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Ticket;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TicketController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $tickets = Ticket::all();
        return view('admin.ticket.index',compact('tickets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function show(Ticket $ticket)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function edit(Ticket $ticket)
    {
        //
        return view('admin.ticket.edit',compact('ticket'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Ticket $ticket)
    {
        $data = $request->all();
        $data['journey_time'] = date('Y-m-d H:i:s', strtotime($request->get('journey_time')));
        $ticket->update($data);
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ticket $ticket)
    {
        //
        Ticket::destroy($ticket->id);
        return redirect()->back();
    }
    public function updateStatus(Request $request)
    {
      Ticket::find($request->get('id'))->update(['status'=>($request->get('data')=='true'?'1':'0')]);
      return 'success';
    }

}

resources/views/admin/ticket/edit.blade.php
@extends('layouts.adminapp')

@section('content')
<div class="app-title">
  <div>
    <h1><i class="fa fa-dashboard"></i> Edit Ticket</h1>
    <p>Edit Ticket that {{$ticket->user->name}} posted at {{date('jS M,Y h:i A',strtotime($ticket->created_at))}}.</p>
  </div>
  <ul class="app-breadcrumb breadcrumb">
    <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i>Setting</li>
    <li class="breadcrumb-item"><a href="{{route('admin.ticket.index')}}">Manage Ticket Posting</a></li>
    <li class="breadcrumb-item"><a href="{{route('admin.ticket.edit',$ticket->id)}}">Edit Ticket</a></li>
  </ul>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="tile">
      <div class="tile-body">
        <form method="post" action="{{route('admin.ticket.update',$ticket->id)}}">
          {{csrf_field()}}
          <input type="hidden" name="_method" value="PUT">
          <div class="row mb-4">
            <div class="col-md-4">
              <label>Source City</label>
              <select class="form-control" name="source_id" id="source" required>
                <option value="{{$ticket->source->id}}" selected>{{$ticket->source->name}}</option>
              </select>
            </div>
            <div class="col-md-4">
              <label>Destination City</label>
              <select class="form-control" name="destination_id" id="destination" required>
                <option value="{{$ticket->destination->id}}" selected>{{$ticket->destination->name}}</option>
              </select>
            </div>
          </div>
          <div class="row mb-4">
            <div class="col-md-4">
              <label>Journey Date</label>
              <div class="form-group">
                  <div class="input-group date" id="datepicker" data-target-input="nearest">
                      <input name="journey_time" type="text" id="journey-date" required class="form-control datetimepicker-input" data-target="#datepicker"/>
                      <div class="input-group-append" data-target="#datepicker" data-toggle="datetimepicker">
                          <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                      </div>
                  </div>
              </div>
            </div>
            <div class="col-md-4">
              <label>Price</label>
              <input class="form-control" type="text" name="price" value="{{$ticket->price}}" required>
            </div>
          </div>
          <div class="row mb-4">
            <div class="col-md-4">
              <label>Bus Operator</label>
              <select class="form-control" name="bus_operator_id" required>
                @foreach(App\BusOperator::all() as $bus_operator)
                <option value="{{$bus_operator->id}}" @if($ticket->bus_operator_id == $bus_operator->id) selected @endif>{{$bus_operator->name}}</option>
                @endforeach
              </select>
            </div>
            <div class="col-md-4">
              <label>Bus Type</label>
              <select class="form-control" name="bus_type_id" required>
                @foreach(App\BusType::all() as $bus_type)
                <option value="{{$bus_type->id}}" @if($ticket->bus_type_id == $bus_type->id) selected @endif>{{$bus_type->name}}</option>
                @endforeach
              </select>
            </div>
          </div>

          </div>
          <div class="row mb-10">
            <div class="col-md-12">
              <button class="btn btn-primary"><i class="fa fa-fw fa-lg fa-check-circle"></i> Save</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
@endsection
@section('additional_css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha18/css/tempusdominus-bootstrap-4.min.css" />
@endsection
@section('footer_scripts')
<script type="text/javascript" src="{{asset('admin_assets/js/plugins/select2.min.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.21.0/moment.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.0-alpha18/js/tempusdominus-bootstrap-4.min.js"></script>
<script type="text/javascript">
(function () {
    $("#datepicker").datetimepicker({
        defaultDate:new Date('{{$ticket->journey_time}}')
    });
    $('#destination').select2({
        placeholder:'Select Destination City',
        ajax: {
            dataType: 'json',
            url: '{{route('search-city1')}}',
            processResults: function (data) {
                // Tranforms the top-level key of the response object from 'items' to 'results'
                return {
                    results: data.items
                };
            }
        }
    });
    $('#source').select2({
        placeholder:'Select Source City',
        ajax: {
            dataType: 'json',
            url: '{{route('search-city1')}}',
            processResults: function (data) {
                // Tranforms the top-level key of the response object from 'items' to 'results'
                return {
                    results: data.items
                };
            }
        }
    });
})();
</script>
@endsection

resources/views/admin/ticket/index.blade.php
@extends('layouts.adminapp')

@section('content')
<div class="app-title">
  <div>
    <h1><i class="fa fa-dashboard"></i> Manage Tickets</h1>
    <p>Manage tickets of all users</p>
  </div>
  <ul class="app-breadcrumb breadcrumb">
    <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i> Setting</li>
    <li class="breadcrumb-item"><a href="{{route('admin.ticket.index')}}">Manage Ticket Posting</a></li>
  </ul>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="tile">
      <div class="tile-body">
        <table class="table table-hover table-bordered" id="sampleTable">
          <thead>
            <tr>
              <th>Posted Date</th>
              <th>Posted By</th>
              <th>Journey Date</th>
              <th>Source City</th>
              <th>Destination City</th>
              <th>Status</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            @foreach($tickets as $ticket)
            <tr>
              <td>{{date('jS M,Y h:i A',strtotime($ticket->created_at))}}</td>
              <td>{{$ticket->user->name}}</td>
              <td>{{date('jS M,Y h:i A',strtotime($ticket->journey_time))}}</td>
              <td>{{$ticket->source->name}}</td>
              <td>{{$ticket->destination->name}}</td>
              <td><div class="toggle"><label><input id="status_{{$ticket->id}}" onclick="setStatus('status_{{$ticket->id}}')" type="checkbox" {{($ticket->status?'checked':'')}}><span class="button-indecator"></span></label></div></td>
              <td>
                <a class="btn btn-primary text-light" href="{{route('admin.ticket.edit',$ticket->id)}}"><i class="fa fa-edit"></i> Edit</a>
                <a class="btn btn-danger text-light" href="#" onclick="onDelete('{{route('admin.ticket.destroy',$ticket->id)}}')"><i class="fa fa-trash"></i> Delete</a>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<form id="delete_form" method="post">
  <input type="hidden" name="_method" value="DELETE">
  {{csrf_field()}}
</form>
@endsection
@section('footer_scripts')
<script type="text/javascript" src="{{asset('admin_assets/js/plugins/jquery.dataTables.min.js')}}"></script>
<script type="text/javascript" src="{{asset('admin_assets/js/plugins/dataTables.bootstrap.min.js')}}"></script>
<script type="text/javascript">$('#sampleTable').DataTable();</script>
<script type="text/javascript">
  function setStatus(id)
  {
    $.ajax({
      url:'{{route('admin.ticket.update_status')}}',
      type:'POST',
      data:{'id':id.split('_')[1],'_token':'{{csrf_token()}}','data':$('#'+id).is(':checked')},
      success:function(result){

      }
    });
  }
  function onDelete(url)
  {
    $('#delete_form').attr('action',url);
    $('#delete_form').submit();
  }
</script>
@endsection