routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'Controller@index');
Route::get('/privacy', 'Controller@privacy');
Route::get('/termsofuse', 'Controller@terms');
Route::get('/faq', 'Controller@faq');
Route::post('/searchresult', 'Controller@find')->name('searchresult');
Route::get('/loadresult','Controller@ajaxPageLoading')->name('loadresult');
Route::get('/getSeatLayout','Controller@getBusLayout');

Auth::routes();

Route::get('/resetPassword','Auth\ForgotPasswordController@showResetUI')->name('resetPassword');
Route::post('/resetPassword','Auth\ForgotPasswordController@sendResetedPassword');

Route::get('/home', 'HomeController@index')->name('dashboard');
Route::post('/update-profile','HomeController@updateProfile')->name('post_update_profile');
Route::post('/update-password','HomeController@updatePassword')->name('post_update_password');

Route::get('sell-ticket','Controller@sellTicket')->name('sellTicket');
Route::post('sell-ticket','Controller@addTicket')->name('post_sellTicket');
Route::get('/search-city','Controller@searchCity')->name('search-city');
Route::get('/search-city1','Controller@searchCity1')->name('search-city1');
Route::post('/subscribe','Controller@subscribe')->name('subscribe');
Route::post('/feedback','Controller@feedback')->name('feedback');
Route::post('/request-ticket','Controller@requestTicket')->name('request-ticket');

Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('admin/', 'Admin\LoginController@showLogin');
Route::post('admin/login', 'Admin\LoginController@login')->name('admin.login');

Route::middleware(['admin'])->prefix('admin')->name('admin.')->group(function () {
    //User Settings
    Route::get('/home', 'Admin\AdminController@index')->name('home');
    Route::post('/update_name_email','Admin\AdminController@updateUsername_Email')->name('update.name.email');
    Route::post('/update_password','Admin\AdminController@updatePassword')->name('update.password');
    Route::get('/logout', 'Admin\LoginController@logout')->name('logout');

    //Ticket Resource
    Route::resource('ticket','Admin\TicketController');
    Route::post('ticket/update_status','Admin\TicketController@updateStatus')->name('ticket.update_status');

    Route::get('user/','Admin\UserController@index')->name('user.index');
    Route::post('user/update_status','Admin\UserController@updateStatus')->name('user.update_status');

    Route::get('feedback/','Admin\FeedbackController@index')->name('feedback.index');
    Route::get('feedback/{feedback}/show','Admin\FeedbackController@show')->name('feedback.show');
    Route::get('feedback/{feedback}/destroy','Admin\FeedbackController@destroy')->name('feedback.destroy');

    Route::get('faq','Admin\FaqController@index')->name('faq.index');
    Route::get('faq/{faq}/destroy','Admin\FaqController@destroy')->name('faq.destroy');
    Route::get('faq/{faq}/edit','Admin\FaqController@edit')->name('faq.edit');
    Route::post('faq/{faq}/update','Admin\FaqController@update')->name('faq.update');
    Route::post('faq/insert','Admin\FaqController@insert')->name('faq.insert');
    Route::get('faq/add','Admin\FaqController@add')->name('faq.add');

    Route::get('subscribe','Admin\SubscribeController@index')->name('subscribe.index');
    Route::get('subscribe/{subscribe}.destroy','Admin\SubscribeController@destroy')->name('subscribe.destroy');

    Route::get('bustype' , 'Admin\BusTypeController@index')->name('bustype.index');
    Route::post('bustype/add' , 'Admin\BusTypeController@insert')->name('bustype.insert');
    Route::get('bustype/{bustype}/destroy','Admin\BusTypeController@destroy')->name('bustype.destroy');
    Route::get('bustype/{bustype}/edit','Admin\BusTypeController@edit')->name('bustype.edit');
    Route::post('bustype/{bustype}/update','Admin\BusTypeController@update')->name('bustype.update');

    Route::get('busoperator' , 'Admin\BusOperatorController@index')->name('busoperator.index');
    Route::post('busoperator/add' , 'Admin\BusOperatorController@insert')->name('busoperator.insert');
    Route::get('busoperator/{busoperator}/destroy','Admin\BusOperatorController@destroy')->name('busoperator.destroy');
    Route::get('busoperator/{busoperator}/edit','Admin\BusOperatorController@edit')->name('busoperator.edit');
    Route::post('busoperator/{busoperator}/update','Admin\BusOperatorController@update')->name('busoperator.update');
});

app/BusOperator.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BusOperator extends Model
{
    //
    protected $guarded = ['id'];
}

app/Http/Controllers/Admin/BusOperatorController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\BusOperator;
class BusOperatorController extends Controller
{
    //
    public function index()
    {
    	$busoperators = BusOperator::all();
    	return view('admin.busoperator.index',compact('busoperators'));
    }
    public function insert(Request $request)
    {
    	BusOperator::create(['name'=>$request->get('name')]);
    	return redirect()->back();
    }
    public function destroy(BusOperator $busoperator)
    {
    	BusOperator::destroy($busoperator->id);
    	return redirect()->back();
    }
    public function edit(BusOperator $busoperator)
    {
    	return view('admin.busoperator.edit',compact('busoperator'));
    }
    public function update(Request $request, BusOperator $busoperator)
    {
    	$busoperator->update(['name'=>$request->get('name')]);
    	return redirect()->back();
    }
}

resources/views/admin/busoperator/edit.blade.php
@extends('layouts.adminapp')

@section('content')
<div class="app-title">
  <div>
    <h1><i class="fa fa-dashboard"></i> Edit Bus Operator </h1>
    <p>Edit bus operator.</p>
  </div>
  <ul class="app-breadcrumb breadcrumb">
    <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i>Setting</li>
    <li class="breadcrumb-item"><a href="{{route('admin.busoperator.index')}}">Manage Bus Types</a></li>
    <li class="breadcrumb-item"><a href="{{route('admin.busoperator.edit',$busoperator->id)}}">Edit Bus Type</a></li>
  </ul>
</div>
<div class="row">
  	<div class="col-md-12">
  		<div class="tile">
  			<div class="tile-body">
  				<form method="POST" action="{{route('admin.busoperator.update',$busoperator->id)}}">
  					{{csrf_field()}}
  					<div class="row" style="margin-bottom: 10px">
  						<div class="col-md-2">
  							<label for="bus_type_name" class="align-right">
  								Bus Operator Name
  							</label>
  						</div>
  						<div class="col-md-8">
  							<input type="text" name="name" value="{{$busoperator->name}}" id="bus_type_name" class="form-control">
  						</div>
  						<button class="btn btn-success col-md-1">Edit</button>
  					</div>
  				</form>
  			</div>
  		</div>
  	</div>
</div>
@endsection

resources/views/admin/busoperator/index.blade.php
@extends('layouts.adminapp')

@section('content')
<div class="app-title">
  <div>
    <h1><i class="fa fa-dashboard"></i> Manage Bus Operators </h1>
    <p>Manage all bus operators in this website.</p>
  </div>
  <ul class="app-breadcrumb breadcrumb">
    <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i>Setting</li>
    <li class="breadcrumb-item"><a href="{{route('admin.busoperator.index')}}">Manage Bus Operators</a></li>
  </ul>
</div>
<div class="row">
  	<div class="col-md-12">
  		<div class="tile">
  			<div class="tile-body">
  				<form method="POST" action="{{route('admin.busoperator.insert')}}">
  					{{csrf_field()}}
  					<div class="row" style="margin-bottom: 10px">
  						<div class="col-md-2">
  							<label for="bus_type_name" class="align-right">
  								Bus Operator Name
  							</label>
  						</div>
  						<div class="col-md-8">
  							<input type="text" name="name" id="bus_type_name" class="form-control" required="">
  						</div>
  						<button class="btn btn-success col-md-1">Add New</button>
  					</div>
  				</form>
  				<table class="table table-hover table-bordered" id="sampleTable">
		          <thead>
		            <tr>
		              <th>Name</th>
		              <th>Created At</th>
		              <th>Action</th>
		            </tr>
		          </thead>
		          <tbody>
		            @foreach($busoperators as $busoperator)
		            <tr>
		              <td>{{$busoperator->name}}</td>
		              <td>{{date('jS M,Y h:i A',strtotime($busoperator->created_at))}}</td>
		              <td>
		                <a class="btn btn-primary text-light" href="{{route('admin.busoperator.edit',$busoperator->id)}}"><i class="fa fa-edit"></i> Edit</a>
		                <a class="btn btn-danger text-light" onclick="destroy('{{route('admin.busoperator.destroy',$busoperator->id)}}')"><i class="fa fa-trash"></i> Delete</a>
		              </td>
		            </tr>
		            @endforeach
		          </tbody>
		        </table>
  			</div>
  		</div>
  	</div>
</div>
@endsection
@section('footer_scripts')
<script type="text/javascript" src="{{asset('admin_assets/js/plugins/jquery.dataTables.min.js')}}"></script>
<script type="text/javascript" src="{{asset('admin_assets/js/plugins/dataTables.bootstrap.min.js')}}"></script>
<script type="text/javascript" src="{{asset('admin_assets/js/plugins/bootstrap-notify.min.js')}}"></script>
<script type="text/javascript" src="{{asset('admin_assets/js/plugins/sweetalert.min.js')}}"></script>
<script type="text/javascript">$('#sampleTable').DataTable();</script>
<script type="text/javascript">
function destroy(url){
  swal({
    title: "Are you sure?",
    text: "Do you want to delete this feedback!",
    type: "warning",
    showCancelButton: true,
    confirmButtonText: "Yes, delete it!",
    cancelButtonText: "No, cancel plx!",
    closeOnConfirm: false,
  }, function(isConfirm) {
    if (isConfirm) {
      document.location.href = url;
    }
  });
}
</script>
@endsection